#!/bin/sh

# build — Build and build dependencies

# Rashell (https://github.com/melusina-org/cl-rashell)
# This file is part of Rashell.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${buildsystem:="org.melusina.rashell/testsuite"}

build_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

build_main()
{
    build_sbcl --eval "
(unless (ql:where-is-system \"${buildsystem}\")
 (push #p\"./\" ql:*local-project-directories*)
 (ql:register-local-projects))"\
		 --eval "(ql:quickload \"${buildsystem}\")"\
		 --eval '(uiop:quit 0)'
}

build_main "$@"

# End of file `build'
