#!/bin/sh

### compile -- Compile and build dependencies

# Rashell (https://github.com/michipili/cl-rashell)
# This file is part of Rashell
#
# Copyright © 2017–2021 Michaël Le Barbier
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

compile_cleanup()
{
    find "${TOPLEVELDIR}" -type f -name '*.fasl' -delete
}

compile_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

compile_main()
{
    compile_cleanup
    compile_sbcl --eval '
(unless (ql:where-is-system "rashell/test")
 (push #p"./" ql:*local-project-directories*)
 (ql:register-local-projects))'\
	      --eval '(ql:quickload "rashell/test")'\
	      --eval '(uiop:quit 0)'
}

compile_main "$@"

### End of file `compile'
