#!/bin/sh

### testsuite -- Run unit tests

# Rashell (https://github.com/michipili/cl-rashell)
# This file is part of Rashell
#
# Copyright © 2017–2021 Michaël Le Barbier
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

test_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

test_main()
{
    test_sbcl --eval '
(unless (ql:where-is-system "rashell/test")
 (push #p"./" ql:*local-project-directories*))'\
	      --eval '(ql:quickload "rashell/test")'\
	      --eval '(if (rashell/test:run-all-tests)(uiop:quit 0)(uiop:quit 1))'
}

test_main "$@"

### End of file `testsuite'
